import Head from "next/head";
import React from "react";

const Education = () => {
  return (
    <div>
      <Head>
        <title>Education</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="p-8">
        <div className="bg-white p-4 rounded-lg shadow-xl py-8 mt-12">
          <h4 className="text-4xl font-bold text-gray-800 tracking-widest uppercase text-center">
            Education
          </h4>
          <p className="text-center text-gray-600 text-sm mt-2">
            Academic Qualifications
          </p>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4 xl:gap-12 px-2 xl:px-12 mt-4">
            <div className="flex space-x-8 mt-8">
              <div>
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  className="h-12 w-12 text-blue-600"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                >
                  <path d="M12 14l9-5-9-5-9 5 9 5z"></path>
                  <path d="M12 14l6.16-3.422a12.083 12.083 0 01.665 6.479A11.952 11.952 0 0012 20.055a11.952 11.952 0 00-6.824-2.998 12.078 12.078 0 01.665-6.479L12 14z"></path>
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="2"
                    d="M12 14l9-5-9-5-9 5 9 5zm0 0l6.16-3.422a12.083 12.083 0 01.665 6.479A11.952 11.952 0 0012 20.055a11.952 11.952 0 00-6.824-2.998 12.078 12.078 0 01.665-6.479L12 14zm-4 6v-7.5l4-2.222"
                  ></path>
                </svg>
              </div>
              <div>
                <h4 className="text-xl font-bold text-gray-700">
                  Birla Institute of Technology , Mesra
                </h4>
                <p className="text-gray-600 my-2">
                  Pursued Integrated Masters in Mathematics and Computing
                </p>
                <a
                  href="https://www.bitmesra.ac.in/"
                  className="text-blue-600 hover:text-blue-800 hover:underline capitalize"
                  title="Read More"
                >
                  Read More
                </a>
              </div>
            </div>

            <div className="flex space-x-8 mt-8">
              <div>
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  className="h-12 w-12 text-blue-600"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="2"
                    d="M21 13.255A23.931 23.931 0 0112 15c-3.183 0-6.22-.62-9-1.745M16 6V4a2 2 0 00-2-2h-4a2 2 0 00-2 2v2m4 6h.01M5 20h14a2 2 0 002-2V8a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z"
                  ></path>
                </svg>
              </div>
              <div>
                <h4 className="text-xl font-bold text-gray-700">
                  JNV Bengaluru Rural
                </h4>
                <p className="text-gray-600 my-2">Class 12th</p>
                <a
                  href="https://navodaya.gov.in/nvs/nvs-school/BANGALORERURAL/en/home/"
                  className="text-blue-600 hover:text-blue-800 hover:underline capitalize"
                  title="Read More"
                >
                  Read More
                </a>
              </div>
            </div>
            <div className="flex space-x-8 mt-8">
              <div>
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  className="h-12 w-12 text-blue-600"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="2"
                    d="M4 7v10c0 2.21 3.582 4 8 4s8-1.79 8-4V7M4 7c0 2.21 3.582 4 8 4s8-1.79 8-4M4 7c0-2.21 3.582-4 8-4s8 1.79 8 4m0 5c0 2.21-3.582 4-8 4s-8-1.79-8-4"
                  ></path>
                </svg>
              </div>
              <div>
                <h4 className="text-xl font-bold text-gray-700">
                  Java Programming: Solving Problems with Software
                </h4>
                <p className="text-gray-600 my-2">
                  I recently completed Java Programming: Solving Problems with
                  Software from Duke University on Coursera. View my certificate
                  here
                </p>
                <a
                  href="https://coursera.org/share/a8270eab4aef15f1e96748106ef79392"
                  className="text-blue-600 hover:text-blue-800 hover:underline capitalize"
                  title="Read More"
                >
                  Read More
                </a>
              </div>
            </div>

            

            <div className="flex space-x-8 mt-8">
              <div>
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  className="h-12 w-12 text-blue-600"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="2"
                    d="M7 21a4 4 0 01-4-4V5a2 2 0 012-2h4a2 2 0 012 2v12a4 4 0 01-4 4zm0 0h12a2 2 0 002-2v-4a2 2 0 00-2-2h-2.343M11 7.343l1.657-1.657a2 2 0 012.828 0l2.829 2.829a2 2 0 010 2.828l-8.486 8.485M7 17h.01"
                  ></path>
                </svg>
              </div>
              <div>
                <h4 className="text-xl font-bold text-gray-700">
                  Logistic Regression with NumPy and Python
                </h4>
                <p className="text-gray-600 my-2">
                  I recently completed Logistic Regression with NumPy and Python
                  from Coursera Project Network on Coursera. View my certificate
                  here
                </p>
                <a
                  href="https://coursera.org/share/f51b2afca42d081f5f0a9ff23bcfca03"
                  className="text-blue-600 hover:text-blue-800 hover:underline capitalize"
                  title="Read More"
                >
                  Read More
                </a>
              </div>
            </div>

            <div className="flex space-x-8 mt-8">
              <div>
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  className="h-12 w-12 text-blue-600"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="2"
                    d="M7 4v16M17 4v16M3 8h4m10 0h4M3 12h18M3 16h4m10 0h4M4 20h16a1 1 0 001-1V5a1 1 0 00-1-1H4a1 1 0 00-1 1v14a1 1 0 001 1z"
                  ></path>
                </svg>
              </div>
              <div>
                <h4 className="text-xl font-bold text-gray-700">
                  Python Data Structures
                </h4>
                <p className="text-gray-600 my-2">
                  completed Python Data Structures from University of Michigan
                  on Coursera. View my certificate here
                </p>
                <a
                  href="https://coursera.org/share/1deef0055a3b97753406db0775363310"
                  className="text-blue-600 hover:text-blue-800 hover:underline capitalize"
                  title="Read More"
                >
                  Read More
                </a>
              </div>
            </div>
            <div className="flex space-x-8 mt-8">
              <div>
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  className="h-12 w-12 text-blue-600"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="2"
                    d="M9 3v2m6-2v2M9 19v2m6-2v2M5 9H3m2 6H3m18-6h-2m2 6h-2M7 19h10a2 2 0 002-2V7a2 2 0 00-2-2H7a2 2 0 00-2 2v10a2 2 0 002 2zM9 9h6v6H9V9z"
                  ></path>
                </svg>
              </div>
              <div>
                <h4 className="text-xl font-bold text-gray-700">
                  Basic Data Descriptors, Statistical Distributions, and
                  Application to Business Decisions
                </h4>
                <p className="text-gray-600 my-2">
                  I completed Basic Data Descriptors, Statistical Distributions,
                  and Application to Business Decisions from Rice University on
                  Coursera. View my certificate here:
                </p>
                <a
                  href="https://coursera.org/share/c780a68879ae8cef9a75e64e0cf64cc8"
                  className="text-blue-600 hover:text-blue-800 hover:underline capitalize"
                  title="Read More"
                >
                  Read More
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Education;
