import Image from "next/image";
import { Inter } from "next/font/google";
import Head from "next/head";
import type { GetServerSideProps, NextPage } from "next";
import { fetchCategories } from "../apis";
import { ICategory, ICollectionResponse } from "../types";
import { AxiosResponse } from "axios";

const inter = Inter({ subsets: ["latin"] });

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Eco Quant</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="container">
          <div className="content mb-4">
            <div className="text-center">
              <p className="text-sky-600 text-5xl">Hello, World!</p>
            </div>
          </div>
          <div className="section-one bg-gray-100 p-4 rounded-lg flex items-center">
            <div className="description flex-1 font-['Open_Sans'] text-xl mr-4">
              <p className="text-gray-600  mb-5">
                I am <span className="text-pink-400">Sanjay</span>
              </p>
              <p className="text-gray-600 hover:text-rose-700 mb-4">
                I work as a Software Engineer and aspire to become a Quant,
                based in Bengaluru, India.
              </p>
              <p className="text-gray-600 hover:text-rose-700 mb-4">
                I create open source projects and write about financial
                mathematics, programming, statistics, data visualisation, and
                related topics
              </p>
            </div>
            <div className="profile-photo w-32 h-32 bg-gray-300 rounded-full mr-8">
              <Image
                src="/sanjay.jpeg"
                width={150}
                height={150}
                alt="Sanjay"
                className="rounded-full"
              ></Image>
            </div>
          </div>

          <style jsx>{`
            .container {
              margin: 2rem auto; /* This will center the container */
              max-width: 1000px; /* Adjust the maximum width as per your requirement */
              padding: 0 1rem; /* Add some padding on the left and right sides */
            }

            .content {
              background-color: #fff; /* Add a background color for the container */
              padding: 1rem; /* Add some padding inside the container */
            }
          `}</style>
        </div>
      </main>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async () => {
  // categories
  const { data: categories }: AxiosResponse<ICollectionResponse<ICategory[]>> =
    await fetchCategories();
  console.log("categories", categories);

  
  return {
    props: {
      categories: {
        items: categories.data,
      },
    },
  };
};

export default Home;
