import Image from "next/image";
import { Inter } from "next/font/google";
import Head from "next/head";
import type { NextPage } from "next";


const inter = Inter({ subsets: ["latin"] });


const Home: NextPage = () => {
  return (
    <div className="main-content">
      <Head>
        <title>Eco Quant</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
        <div className="content mb-4">
          <div className="text-center">
            <p className="text-sky-600 text-5xl mt-10">Hello, World!</p>
          </div>
        </div>
        <div className="section-one p-4 rounded-lg flex md:flex-row items-center">
          <div className="description flex-1 font-['Open_Sans'] text-xl md:mr-4">
            <p className="text-gray-600 mt-10 mb-10">
              I am <span className="text-pink-400">Sanjay</span>
            </p>
            <p className="text-gray-600 hover:text-rose-700 mb-10">
              I work as a Software Engineer and aspire to become a Quant,
              based in Bengaluru, India.
            </p>
            <p className="text-gray-600 hover:text-rose-700 mb-10">
              I create open source projects and write about financial
              mathematics, programming, statistics, data visualization, and
              related topics.
            </p>
          </div>
          <div className="profile-photo md:w-40 md:h-40 bg-gray-300 rounded-full mx-auto md:mx-0 md:self-center">
            <Image
              src="/sanjay.jpeg"
              width={160}
              height={160}
              alt="Sanjay"
              className="rounded-full"
            />
          </div>
        </div>
      </div>

      <style jsx>{`
        .container {
          margin: 2rem auto;
          max-width: 1000px;
          padding: 0 1rem;
        }

        .content {
          background-color: #fff;
          padding: 1rem;
        }

        .main-content {
          margin-top: 6rem;
          flex: 1;
        }

        @media (max-width: 767px) {
          .section-one {
            flex-direction: column-reverse;
          }

          .description {
            margin-bottom: 1rem;
          }
        }
      `}</style>
    </div>
  );
};

export default Home;
